import {Bell,BookOpen,CalendarClock,ChartNoAxesCombined,ClipboardCheck,Database,FileClock,Home,LogOut,Menu,ScanLine,Settings2,ShieldAlert,Users,Workflow, X, Search} from 'lucide-react'
import {useState} from 'react';import type {ReactNode} from 'react';import{Link,useLocation}from'react-router-dom';import type {User} from'../App'

const nav=(role:User['role'])=>({student:[['Overview','/student',Home],['Attendance','/student#attendance',ClipboardCheck],['Scan & Verify','/student#scan',ScanLine],['Actions','/student#actions',Workflow],['Notifications','/student#notifications',Bell]],faculty:[['Overview','/faculty',Home],['Live Attendance','/faculty#live',ScanLine],['At-Risk Students','/faculty#risk',ShieldAlert],['Sessions','/faculty#sessions',CalendarClock],['Corrections','/faculty#requests',FileClock]],hod:[['Overview','/hod',Home],['Department Intelligence','/hod#intelligence',ChartNoAxesCombined],['Interventions','/hod#interventions',Workflow],['Reports','/hod#reports',BookOpen]],admin:[['Overview','/admin',Home],['People & Roster','/admin#people',Users],['Audit & Governance','/admin#audit',ShieldAlert],['System Health','/admin#health',Database],['Policy','/admin#policy',Settings2]]}[role])
export default function Shell({user,onLogout,children}:{user:User;onLogout:()=>void;children:ReactNode}){const [open,setOpen]=useState(false);const loc=useLocation();const items=nav(user.role);return <div className="app-shell">
 <aside className={`sidebar ${open?'show':''}`}><div className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></div><div className="brand"><div className="logo">A<span>+</span></div><div><strong>AttendX</strong><small>Attendance Intelligence</small></div></div><div className="section-label">Workspace</div><nav>{items.map(([label,to,Icon]:any)=><Link key={label} onClick={()=>setOpen(false)} className={loc.pathname+loc.hash===to?'active':''} to={to}><Icon size={18}/><span>{label}</span></Link>)}</nav><div className="sidebar-bottom"><div className="privacy"><ShieldAlert size={15}/><div><b>Privacy by design</b><span>Minimal collection. Human review for flags.</span></div></div><button className="logout" onClick={onLogout}><LogOut size={16}/>Sign out</button></div></aside>
 <main className="main-area"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="search"><Search size={16}/><input placeholder="Search attendance, students, sessions…"/></div><div className="top-actions"><span className="network"><i/>Live</span><button className="icon-button"><Bell size={19}/></button><div className="user-menu"><div className="avatar">{user.full_name.slice(0,1)}</div><div className="user-meta"><b>{user.full_name}</b><span>{user.role.toUpperCase()}{user.section?` · ${user.section}`:''}</span></div></div></div></header><div className="content">{children}</div></main>
 <div className={`mobile-overlay ${open?'show':''}`} onClick={()=>setOpen(false)}/>
 </div>}
