import{useEffect,useState}from'react';import{QRCodeSVG}from'qrcode.react';import{CheckCircle2,Play,RefreshCcw,WifiOff}from'lucide-react';import{api}from'../lib/api';import{PageHeader,Stat,Status,Button,TrustBadge,Insight,Empty}from'../components/UI';import type{User}from'../App';
export default function Faculty({user}:{user:User}){const[assign,setAssign]=useState<any[]>([]);const[risk,setRisk]=useState<any[]>([]);const[sessions,setSessions]=useState<any[]>([]);const[qr,setQr]=useState<any>();const[session,setSession]=useState<any>();const[error,setError]=useState('');const[requests,setRequests]=useState<any[]>([]);
 const load=()=>{api<any[]>('/faculty/assignments').then(setAssign);api<any[]>('/faculty/risk').then(setRisk);api<any[]>('/faculty/sessions').then(setSessions)};useEffect(()=>{load();api<any[]>('/requests/corrections').then(setRequests)},[])
 const start=async()=>{setError('');if(!assign[0])return;try{const a=assign[0];const s=await api<any>('/faculty/sessions',{method:'POST',body:JSON.stringify({subject_id:a.subject_id,section_id:a.section_id,session_date:new Date().toISOString().slice(0,10),start_time:'10:00',end_time:'11:00'})});setSession(s);const q=await api<any>(`/faculty/sessions/${s.id}/qr`);setQr(q);load()}catch(e){setError(e instanceof Error?e.message:'Unable to start')}}
 useEffect(()=>{if(!session)return;const t=setInterval(async()=>setQr(await api<any>(`/faculty/sessions/${session.id}/qr`)),5000);return()=>clearInterval(t)},[session])
 return <div><PageHeader eyebrow="Faculty workspace" title="Run the class, then act on the signals." desc="Start attendance in seconds, see emerging risk, and review suspicious sessions with evidence." action={<Button onClick={start}><Play size={15}/>Start live attendance</Button>}/>{error&&<Insight kind="danger" title="Couldn’t start session">{error}</Insight>}<div className="stats-grid"><Stat label="Students needing attention" value={risk.filter(r=>r.state!=='Safe').length} note="Across your assigned subjects"/><Stat label="Critical" value={risk.filter(r=>r.state==='Critical').length} note="Human review required"/><Stat label="Live sessions" value={sessions.filter(s=>s.status==='open').length} note="Currently accepting attendance"/><Stat label="Verification" value="Layered" note="QR + device + session rules"/></div>
 <section id="live" className="panel live-panel"><div className="section-head"><div><h2>Live attendance room</h2><p>Display the rotating classroom QR while students check in from their phones.</p></div>{session&&<TrustBadge text="Signed session"/>}</div>{session&&qr?<div className="live-room"><div className="qr-placeholder"><QRCodeSVG value={qr.payload} size={190} bgColor="#ffffff" fgColor="#162033" includeMargin/><span>QR refreshes every {qr.expires_in}s</span></div><div className="live-details"><span className="live-dot"><i/>Session open</span><h3>{assign.find(a=>a.subject_id===session.subject_id)?.subject||'Active class'}</h3><p>Students see the same QR but each token is server-signed and short-lived.</p><div className="check-list"><span><CheckCircle2 size={16}/> Duplicate attendance prevented</span><span><CheckCircle2 size={16}/> Browser device registered</span><span><CheckCircle2 size={16}/> Session window enforced</span></div><button className="btn secondary" onClick={async()=>{await api(`/faculty/sessions/${session.id}/close`,{method:'POST'});setSession(null);setQr(undefined);load()}}>Close session</button></div></div>:<div className="empty live-empty"><WifiOff size={22}/><div><b>No live session yet</b><span>Start attendance to open a signed QR session.</span></div></div>}</section>
 <section id="risk" className="panel"><div className="section-head"><div><h2>At-risk students</h2><p>Prioritize the students where a timely conversation can still change the outcome.</p></div><button className="btn ghost" onClick={load}><RefreshCcw size={15}/>Refresh</button></div>{risk.length?<div className="risk-table table-wrap"><table><thead><tr><th>Student</th><th>Subject</th><th>Attendance</th><th>Projected</th><th>Runway</th><th>Why</th></tr></thead><tbody>{risk.map((r,i)=><tr key={i}><td><b>{r.student}</b><span className="cell-sub">{r.student_id}</span></td><td><b>{r.code}</b><span className="cell-sub">{r.name}</span></td><td><strong>{r.current_percent}%</strong><span className="cell-sub">threshold {r.threshold}%</span></td><td>{r.projected_end_percent}%</td><td>{r.remaining} left · {r.safe_miss} safe miss</td><td><Status state={r.state}/><span className="cell-sub reason-text">{r.reason}</span></td></tr>)}</tbody></table></div>:<Empty icon={<CheckCircle2 size={22}/>} title="No emerging risk" desc="Assigned subjects are currently within expected ranges."/>}</section>
 <section id="sessions" className="panel"><div className="section-head"><div><h2>Session history</h2><p>Operational record of the classes you’ve taken.</p></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Subject</th><th>Section</th><th>Present</th><th>Rate</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{new Date(s.date).toLocaleDateString()}</td><td><b>{s.code}</b><span className="cell-sub">{s.subject}</span></td><td>{s.section}</td><td>{s.present}/{s.total||'—'}</td><td>{s.rate}%</td></tr>)}</tbody></table></div></section>
 </div>}
